# Generated by Django 6.0 on 2025-12-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio', models.FileField(upload_to='audios/')),
                ('video', models.FileField(upload_to='videos/')),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
