# Generated by Django 6.0 on 2025-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_contact_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
