# Generated by Django 6.0 on 2026-01-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='d_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='d_des',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
