# Generated by Django 6.0 on 2026-01-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addemployee_d_code_addemployee_d_des_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userquery',
        ),
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(default='No subject', max_length=50),
            preserve_default=False,
        ),
    ]
