# Generated by Django 6.0 on 2026-01-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_userquery_query_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(default='panding', max_length=10),
        ),
    ]
