# Generated by Django 6.0 on 2026-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_query_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
