# Generated by Django 6.0 on 2026-01-16 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_query_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(error_messages='Enter validate name', max_length=20, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
