# Generated by Django 6.0 on 2026-01-16 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_query_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(error_messages='Enter validate name', max_length=100, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
