# Generated by Django 6.0 on 2026-01-17 06:48

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_addemployee_name_alter_query_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='contact',
            field=models.CharField(max_length=15, validators=[app.models.Emp_contact]),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Name cannot exceed 10 characters.', 'min_length': 'Name must contain at least 3 characters.'}, max_length=100, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
