# Generated by Django 6.0 on 2026-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
