# Generated by Django 6.0 on 2026-05-18 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_addemployee_joining_date_addemployee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Name cannot exceed 20 characters.', 'min_length': 'Name must contain at least 3 characters.'}, max_length=100, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
