# Generated by Django 6.0 on 2026-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_addemployee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
