# Generated by Django 6.0 on 2026-05-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_attendance_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_fine',
            field=models.IntegerField(default=0),
        ),
    ]
