# Generated by Django 6.0 on 2026-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_attendance_late_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='final_salary',
            field=models.FloatField(default=0),
        ),
    ]
