# Generated by Django 6.0 on 2026-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
