# Generated by Django 6.0 on 2026-06-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_task_progress_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.addemployee'),
        ),
    ]
