# Generated by Django 6.0 on 2026-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_new_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
